org: zao95
app: serverless-study
service: serverless-study

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

functions:
  test:
    handler: dist/handler.invoke
    events:
      - http:
          path: /
          method: get
  apple:
    handler: dist/handler.invoke
    events:
      - http:
          path: /apple
          method: post

plugins:
  - serverless-offline
  - serverless-cloudformation-sub-variables
  - serverless-prune-plugin
  - serverless-domain-manager