org: zao95
app: serverless-study
service: serverless-study

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ap-northeast-1

functions:
  test:
    handler: dist/handler.invoke
    events:
      - http:
          path: /
          method: get
  users:
    handler: dist/handler.invoke
    events:
      - http:
          path: /users
          method: post

plugins:
  - serverless-offline
  - serverless-cloudformation-sub-variables
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3